Tests/ZMLogTests.m
This test was printing 2000 lines of codes to console. Probably 3 lines are enough. @daehn ?
=> Remove verbose test output

Source/ZMSAppleSystemLoggerWrapper.m
Logs at `debug` level generated from Swift code were not visible in iPhone console
Make sure logs are forced to at least `ASL_LEVEL_NOTICE`, which is the minimum for it to be displayed in phone console
Can't easily test this unfortunately
=> Make logs at debug level visible in phone console

Source/WireSystem.h, Source/ZMSLogNotifications.h, Source/ZMSLogNotifications.m, WireSystem.xcodeproj/project.pbxproj
Adding notifications for request loops and inconsistent state. 
These notifications were previously defined in the `wire-ios-sync-engine` but I've moved them here so that they can be used in all the frameworks. I've also renamed them so that this change only needs to be minor change.
=> Logging notifications

Source/ZMSLog+Recording.swift
It is necessary for AVS debugging to see the more detailed timing of the log entries.
I've added the milliseconds to the logs by using a static `DateFormatter` object instead of istantiating the `Date` object directly. The new date format is `yyyy-MM-dd HH:mm:ss.SSSS Z`.
=> ZIOS-9925: Add milliseconds to the log entries

.circleci/config.yml, fastlane/Fastfile
Some functionality was still missing after migrating to Fastlane scripts - uploading test coverage info and running Danger.
After tests running `fastlane post_test` step.
Needs to be updated when this is merged:
=> Added post test step

Source/ZMSAsserts.swift
Useful protocol can be used across the SE, so more useful to have it in the wire-ios-system.
=> Moved PrivateStringConvertible to WireSystem

Source/Cache.swift, Source/CircularArray.swift, Tests/CacheTests.swift, WireSystem.xcodeproj/project.pbxproj
This adds NSCache-like generic cache implementation. Known limitations: no way to discard the single element from cache.
Supports the cost and element count constraints.
=> Cache implementation based on CircularArray

Source/ZMSAsserts.swift
* Similar to `preconditionFailure` this `requireInternalFailure` does not need a condition and will always terminate (useful in guards where the condition was already checked beforehand or example).
=> Add requireInternalFailure function not needing a condition

Source/ZMSLog+Levels.swift, Source/ZMSLog.swift
New logging system introduced with iOS 10 supports some more features and formatting of logs in console.
The old logs still go through the new subsystem so we use it only on iOS9.
=> Adapt current logging system to use os.log

Source/ZMSLog+Recording.swift, Source/ZMSLog.swift, Tests/ZMLogTests.swift
Some log messages would be displayed in the log in such a way that there seems to be a gap between events – for example, the timestamp would make it seem that the event happened 4 seconds after when it actually happened.
When logging the message to disk, we prepend the current date to the message. However, the current date at that time of saving the log to disk is different from the current date when the event actually happened, because logging is done asynchronously.
Save the timestamp of the log message at the moment we enqueue its logging, instead of using the current date at the time of saving to disk.
=> Fix erratic log message timestamp

Source/SafeForLoggingStringConvertible.swift, Source/SanitizedString.swift, Source/ZMSAsserts.swift, Source/ZMSLog+Recording.swift, Source/ZMSLog.swift, Source/ZMSLogging.h, Tests/SanitizedLogTests.swift, Tests/SanitizedStringTests.swift, Tests/ZMLogTests.swift, WireSystem.xcodeproj/project.pbxproj
We would like to add logs for public builds, but we need to avoid printing any sensitive data. Simply by printing for example `ZMUser` we could leak their email address.
Added a new method in our logging class - `publicLog()`. It accepts string literals (which we consider safe) and any object that implements `PrivateStringConvertible` protocol. It is a compile error if we try to pass regular object.
We will have to add `PrivateStringConvertible` conformance for things like `URL` and `Data` in this framework.
=> Public logging

Source/ZMSLog+Recording.swift, Tests/ZMLogTests.swift
When logging something with a newline character at the end we would have an empty line in logs. This hurts readability.
We would always append newline to each log entry.
Append newline only if it is missing.
=> Adding newline to log only if it does not have one

Source/ZMSLog+Recording.swift
No log is logged when running the app.
After https://github.com/wireapp/wire-ios-system/pull/43, the logging is disabled since `isRunningSystemTests` == false when running the app.
Disable that line.
@nicorsm in `ZMLogTests.swift` we have some tests related to log files, should we make exceptions for those cases?
=> Fix: Enable logs when running the app

Source/ZMSLog+Recording.swift, Source/ZMSLog.swift
If many logs are written this will block core data from saving. If there was a connecting call, which produces hundreds of log statements, then this could block the save call for several seconds.
We are writing to disk on every log statement. 
Only flush the log file to disk before we are reading it.
I also turned a few computed properties into static properties to avoid re-recreating them on every log statement.
=> Improve performance of logging to a file

Source/ZMSAsserts.swift
In the crash logs, different kinds of crashes are grouped as the same kind.
`fatalError` has no `file` and `line` parameters
Fill in the parameters.
Correct `file` 's type to `StaticString`
=> include file and line in fatalError

Source/ZMSLog.swift
When writing a test, I was making the assumption that when I perform the following sequence of actions:
```
ZMSLog.debug("log statement 1")
ZMSLog.debug("log statement 2")
ZMSLog.sync()
```
I can rely on the fact that both log statements have been saved after `sync()` has been performed. This was not true.
When writing a log statement two nested `async` operations are performed, first in `logEntry()` and then again in `appendToCurrentLog()`. This makes the `sync()` method useless since it will always only wait for the first async operation.
Remove the `async` invocation in `appendToCurrentLog()` it's already executing on the `logQueue`. `appendToCurrentLog()` is only called from the `logEntry()` code path. 
To make sure that's also the case in the future I'm also changing …
=> [Fix] race condition between writing logs and performing the sync() operation

Source/Cache.swift, Tests/CacheTests.swift
- Signal if values where purged upon inserting a new value, by returning a boolean in the `set(value:for:cost:)` method.
- Document public methods
=> [Feature] Signal if values where purged upon inserting a new value

Source/Cache.swift, Tests/CacheTests.swift
Purging the cache for the second time could cause a force unwrap to crash the app.
The cache contains two collections, firstly `cache` which is a dictionary for fast lookup of values, and secondly a `cacheBuffer` which contains the keys for iteration and is used to enforce size limits of the cache.
When an element is added to the cache that causes the maximum cost to be exceeded, the cache will purge enough elements to reduce the cost to below the maximum threshold. It does this by iterating through the keys in the `cacheBuffer`, removing the key from the `cache` dictionary and then subsequently recalculating the `cacheBuffer` to remove the discarded keys.
The crash is caused when purging the cache for the second time, we encounter a key in the `cacheBuffer` that has already been deleted …
=> [Fix] Don't crash when purging cache multiple times

Source/SanitizedString.swift, Tests/SanitizedStringTests.swift
Add interpolation and concatenation of `SanitizedString`. Before this PR, a `SanitizedString` itself could not be used in string interpolation to create a `SanitizedString`.
=> Add interpolation and concatenation of SanitizedString

Resources/Configurations/zmc-config/project-common.xcconfig, WireSystem.xcodeproj/project.pbxproj
When running test on M1 Mac, test can not started.
`The bundle “WireSystem Tests” couldn’t be loaded because it doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.`
Add support for arm64 arch for simulator.
=> fix run time error when test with m1 mac

.github/workflows/bumpVersion.yml
The Jenkins GitHub comment monitoring is unstable and some times does not trigger release 
Possible reasons: unstable connection between Jenkins and Github/Jenkins plugin is outdated/some API limitation changes of Github...
We can archive same function with Github actions `anothrNick/github-tag-action`. 
The action performs following steps:
When `develop` branch has pushed new commit
1. clone the repo shallowly
2. check the commit info, if the author is `iosx+bot@wire.com`(Jenkins pipeline commit) or the commit message is  contains `[skip release]` String, exit
3. dry run `github-tag-action` to get the next version 
4. update the `version.xcconfig` file with the next version, commit and push the change (use `[skip ci]` to prevent CI run repeatedly in next step )
5.run `github-tag-action` …
=> Add bump version GitHub action

Resources/Configurations/zmc-config/ios.xcconfig
clean up VALID_ARCHS which is no long used in Xcode 12
=> clean up VALID_ARCHS
